# mpvfin configuration file
# This file should be placed in your mpv script-opts directory: ~/.config/mpv/script-opts/mpvfin.conf

# Jellyfin Server URL (e.g. http://localhost or https://my.jellyfin.server)
SERVER_URL=https://media.danielepintore.it
# Jellyfin Server Port
SERVER_PORT=443

# Your Jellyfin username
USERNAME=daniele
# Your Jellyfin password
PASSWORD=guru-scurvy-caterer

# Absolute path to store cached images. Leave empty for default (~~/jellyfin_images)
image_path=/home/daniele/.cache/mpv-jellyfin

# Set to "on" to completely hide images
hide_images=

# Spoilers protection (hides plot and other sensitive info for unwatched items)
hide_spoilers=on

# How to handle unwatched episode images. 
# "blur" (blurs unwatched episodes), "hide" (doesn't show image), or "off" (always shows images)
image_spoiler=blur

# Set to "on" to open the mpvfin menu by default when mpv starts
show_by_default=

# Set to "on" to show the menu automatically when mpv is idle
show_on_idle=

# Set to "off" to disable automatic playlist queueing for multi-episode folders
use_playlist=on

# UI Color overrides (Hex codes without the # symbol)
colour_default=FFFFFF
colour_selected=FF
colour_watched=A0A0A0

# Default sorting mode (0 = Default, 1 = Date Added, etc)
sort_mode=0
