# NVIDIA NIS Recommended for Performance
CTRL+3 no-osd change-list glsl-shaders set "~~/shaders/NIS_Main.glsl"; show-text "Nvidia NIS: Enabled"

# FSR CNNX (Recommended for live action)
CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"; show-text "FSRCNNX: Enabled"

# Enable Anime4K (Mode A)
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"; show-text "Anime4K: Enabled"

# Disable all shaders
CTRL+0 no-osd change-list glsl-shaders clr ""; show-text "Disabled all shaders"
