$noctalia_ipc = uwsm app -- qs -c noctalia-shell ipc call

# Volume
binde =, XF86AudioLowerVolume, exec, $noctalia_ipc volume decrease
binde =, XF86AudioRaiseVolume, exec, $noctalia_ipc volume increase
bind =, XF86AudioMute, exec, $noctalia_ipc volume muteOutput

# Mic volume
binde =SUPER,XF86AudioLowerVolume, exec, amixer -q set Dmic0 3%-
binde =SUPER,XF86AudioRaiseVolume, exec, amixer -q set Dmic0 3%+
#binde =,XF86AudioMicMute, exec, amixer -q set Dmic0 toggle
binde =,XF86AudioMicMute, exec, $noctalia_ipc volume decrease

#Screen brightness
binde =,XF86MonBrightnessDown, exec, $noctalia_ipc brightness decrease
binde =,XF86MonBrightnessUp, exec, $noctalia_ipc brightness increase

# Shutdown menu
bind =SUPER,Delete,exec, $noctalia_ipc sessionMenu toggle 

# Noctalia settings menu
bind =SUPER,Home,exec, $noctalia_ipc settings toggle

# Do not disturb
bind =, XF86NotificationCenter, exec, $noctalia_ipc notifications toggleDND

# Media controls
bind =, XF86PickupPhone, exec, playerctl previous
bind =, XF86HangupPhone, exec, playerctl play-pause
bind =, XF86Favorites, exec, playerctl next
