config_version = 2

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.0
    capsule = true
    capsule_border = "outline"
    capsule_fill = "surface"
    capsule_opacity = 0.5
    capsule_padding = 9.0
    end = [ "volume", "brightness", "clipboard", "notifications", "network", "bluetooth", "battery", "control-center" ]
    margin_edge = 5
    margin_ends = 0
    padding = 5
    shadow = false
    start = [ "tray", "caffeine", "group:g1", "workspaces" ]
    thickness = 35
    widget_spacing = 2

        [bar.default.monitor."ASUSTek COMPUTER INC XG27AQWMG W2LMTF013105"]
        auto_hide = true
        center = [ "clock", "disable_secondary_monitor" ]
        reserve_space = false
        show_on_workspace_switch = false

        [[bar.default.capsule_group]]
        border = "outline"
        fill = "surface"
        id = "g1"
        members = [ "cpu", "temp", "ram", "sysmon" ]
        opacity = 0.55000001192092896
        padding = 6.0

[brightness]
enable_ddcutil = true

[calendar]
enabled = true

    [calendar.account.personal_google]
    color = "primary"
    name = "Personal"
    type = "google"

    [calendar.account.subscription_srdnlen]
    name = "Srdnlen"
    server_url = "https://calendar.google.com/calendar/ical/ab212014bb50a1d7164949b59351795bbfebea2f64f0ddcf95f02c074937c245%40group.calendar.google.com/private-e5c99bfe4639dea3da05d4687d0d5f74/basic.ics"
    type = "ics"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "dark_mode"

[desktop_widgets]
schema_version = 1
widget_order = [ "desktop-widget-0000000000000001" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    cx = 1461.5
    cy = 919.3074951171875
    output = "eDP-1"
    rotation = 0.0
    scale = 1.2566845417022705
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = true
        background_opacity = 0.54000000000000004

[hooks]
wallpaper_changed = "ln -sf \"$(noctalia msg wallpaper-get)\" ~/.config/hypr/wallpapers/.current-background.jpg"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 60

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 90

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 66

[location]
address = "Cagliari"

[lockscreen]
enabled = false

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-5",
    "lockscreen-login-box@HDMI-A-5",
    "lockscreen-login-box@DP-3",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1321.0
    output = "DP-3"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1321.0
    output = "DP-5"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-5".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-5"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "HDMI-A-5"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-5".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 800.0
    cy = 788.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 192.0
    box_width = 448.0
    cx = 800.0
    cy = 180.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        clock_style = "digital"
        shadow = false

[shell]
avatar_path = "/home/daniele/.config/avatar.png"
font_family = "JetBrainsMono NF"
launch_apps_custom_command = "uwsm-app -- $CMD"
screen_time_enabled = true
settings_show_advanced = true

    [shell.launcher]
    categories = false

    [shell.panel]
    background_opacity = 0.99999997764825821
    clipboard_placement = "floating"
    control_center_placement = "floating"
    launcher_categories = false
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"
    wallpaper_placement = "floating"

    [[shell.session.actions]]
    action = "command"
    command = "hyprlock --no-fade-in"
    enabled = true
    glyph = "lock"
    label = "Lock"
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Ayu"
community_palette = "Tokyo Night Moon"
mode = "dark"
pure_black_dark = true
source = "wallpaper"
wallpaper_scheme = "m3-rainbow"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "hyprland", "qt" ]

[wallpaper]
directory = "/home/daniele/.config/hypr/wallpapers"
transition = [ "fade" ]
transition_duration = 300

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/daniele/.config/hypr/wallpapers/Abstract 1.jpg"

    [wallpaper.last]
    path = "/home/daniele/.config/hypr/wallpapers/Abstract 1.jpg"

    [wallpaper.monitors.DP-3]
    path = "/home/daniele/.config/hypr/wallpapers/wwdc-2023-8k-swirls-3840x2160-12596.jpg"

    [wallpaper.monitors.DP-5]
    path = "/home/daniele/.config/hypr/wallpapers/Abstract 1.jpg"

    [wallpaper.monitors.HDMI-A-5]
    path = "/home/daniele/.config/hypr/wallpapers/abstract-square-glass-forms-3d-y5-3840x2160.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/daniele/.config/hypr/wallpapers/continental-down.jpg"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/daniele/.config/hypr/wallpapers/wwdc-2023-8k-swirls-3840x2160-12596.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-rainbow"

    [[wallpaper.favorite]]
    path = "/home/daniele/.config/hypr/wallpapers/Mac-Pro-macOS-Catalina-Wallpaper.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/daniele/.config/hypr/wallpapers/abstract-square-glass-forms-3d-y5-3840x2160.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-rainbow"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/daniele/.config/hypr/wallpapers/colorful-3d-shapes-of-abstract-au-3840x2160.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

[widget.battery]
capsule = true

[widget.bongocat]
script = "scripts/bongocat.lua"
type = "scripted"

[widget.clock]
format = "{:%H:%M %a, %b %d}"

[widget.control-center]
glyph = "baseline-density-medium"

[widget.cpu]
display = "text"

[widget.disable_secondary_monitor]
glyph = "device-desktop"
type = "custom_button"

[widget.ram]
display = "text"

[widget.screen_recorder]
script = "scripts/screen_recorder.lua"
type = "scripted"

[widget.sysmon]
display = "text"
stat = "disk_pct"

[widget.temp]
display = "text"

[widget.tray]
anchor = true
detached_panel = true
drawer = true
drawer_columns = 5
hidden = [ "Xwayland Video Bridge_pipewireToXProxy" ]